### ISSUE TITLE
This package is empty

### ISSUE THREAD

**Issue by siebenkopf** [Vastlab/libMR#1]
So far, the libMR package is empty. Should we upload some code here?

**Comment by abhijitbendale** [comment]
https://github.com/Vastlab/liblinear I think this is the actual link.

**Comment by siebenkopf** [comment]
? The libMR and the liblinear packages are completely independent, or did I miss something here?

I think, there are still some legal issues with uploading the code of libMR. We'll upload the code as soon as these issues are solved.

**Comment by siebenkopf** [comment]
not any more.
