### ISSUE TITLE
How to use save() and load() function of Libmr Metarecognition class to save and load the model.

### ISSUE THREAD

**Issue by vaibhavkulk** [Vastlab/libMR#11]
Hello,

I am using the C++ package of libmr by using android JNI in my application,I am able to use it successfully for training(fitting) and testing(getting probability). But after training the EVM by using Libmr FitLow() function, I want to save it so later I can only call ReNormalize() function to check the probability. 

1.  MetaRecognition  mMetaRecognition = new MetaRecognition();  
2.    mMetaRecognition.FitLow(mInputArray, mInputArray.length, 10);
After this I want to save the the model Please guide me in the above mentioned direction.
In my case I am creating N numbers MetaRecognition object to fitting the data.

**Comment by siebenkopf** [comment]
There are various ways on how to save and load data from the MetaRecognition package: https://github.com/Vastlab/libMR/blob/master/libMR/MetaRecognition.h#L108
Which function to use depends heavily on how/where you want to store the data. If you want to store it in a single file, you can use the `Save(char* filename)` function. If you want to store several `MetaRecognition` objects in one file, you might want to use:

```
MetaRecognition mr1();
MetaRecognition mr2();
...
FILE* f = fopen("filename");
mr1.save(f);
mr2.save(f);
```
or alternatively:
```
std::ofstream f("filename", std::ios::binary);
f << mr1 << mr2;
```
Loading will be similar.
