### ISSUE TITLE
pip install failed:   pip install libmr

### ISSUE THREAD

**Issue by ZhenLiuBuaa** [Vastlab/libMR#12]
i use anaconda to  create a clean env (python==3.6.8) and have piped install packages in requirement.txt. But when i pip install libmr, it says "'Extension' object is not iterable"
the log is :

Collecting libmr
  Cache entry deserialization failed, entry ignored
  Using cached https://files.pythonhosted.org/packages/f3/48/f9d43abb742cbebec15933a052042da84d682da2142e803a0c1fa4524210/libmr-0.1.9.zip
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-ht5g3565/libmr/setup.py", line 17, in <module>
        language="c++",
      File "/home/lz/.conda/envs/polar_sar/lib/python3.6/site-packages/Cython/Build/Dependencies.py", line 579, in cythonize
        aliases=aliases)
      File "/home/lz/.conda/envs/polar_sar/lib/python3.6/site-packages/Cython/Build/Dependencies.py", line 503, in create_extension_list
        explicit_modules = set([m.name for m in patterns if isinstance(m, Extension)])
    TypeError: 'Extension' object is not iterable
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-ht5g3565/libmr/
You are using pip version 9.0.1, however version 20.3.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

**Comment by siebenkopf** [comment]
Sorry, I cannot reproduce your issue. Can you maybe update your environment to use the latest versions of all required packages, especially `cython` and `pip`?
If this does not help, could you please provide more details on your setup?

**Comment by ZhenLiuBuaa** [comment]
Thanks very. Everything is ok after i upgrate my cython.
