### ISSUE TITLE
#include <malloc.h> error in MacOS

### ISSUE THREAD

**Issue by samlaf** [Vastlab/libMR#3]
I get this error when running "pip3 install libmr" in MacOS.

```
  libMR/weibull.c:33:10: fatal error: 'malloc.h' file not found
  #include <malloc.h>
           ^~~~~~~~~~
  1 error generated.
  error: command 'clang' failed with exit status 1

  ----------------------------------------
  Failed building wheel for libmr
  Running setup.py clean for libmr
Failed to build libmr
```

I followed https://github.com/RIOT-OS/RIOT/issues/2361 added a preprocessor if statement in weibull.c:
```
#if defined(__MACH__)
#include <stdlib.h>
#else 
#include <malloc.h>
#endif
```

The "real" posix malloc is defined in `#include <stdlib.h>`, so this seems to fix my problem.

**Comment by siebenkopf** [comment]
I finally found the time to work on this. Actually, the `malloc.h` header is non-standard and deprecated. Just including `stdlib.h` is sufficient. Since `stdlib.h` was already included, I just removed the `malloc.h` in ddcdd5c7063926aae740154f6171107b5b04d4e0
